// Instructions:
// Simple number guessing game: guess a randomly generated number between 1 and 10.
// The user has three attempts to guess the correct number.
// After each guess, provide feedback: too high, too low, or correct.

// --------------------
// Game State Variables
// --------------------

let randomNumber = Math.floor(Math.random() * 10) + 1; // generates random number between 1 and 10
let guessCount = 0; // number of valid guesses made
let guessLimit = 3; // user can now set the maximum number of guesses allowed

// Create an array to store attempt history for scoreboard
window.attemptHistory = []; // initialize attempt history

// Main function to check the user's guess against the random number

// get and validate user input

function checkGuess() {
  // Prevent guessing if controls are disabled (defensive)
  const guessElCheck = document.getElementById('userGuess');
  const guessBtnCheck = document.getElementById('guessBtn');
  if ((guessElCheck && guessElCheck.disabled) || (guessBtnCheck && guessBtnCheck.disabled)) return;

// get user input
  const userInput = document.getElementById('userGuess').value; // assume an input field with id 'userGuess'
  if (!userInput) {
    alert('Enter a number first!'); 
    return; // no input provided
  }

  // validate input range
  const guess = Number(userInput); // convert input to number
  
  if (isNaN(guess) || guess < 1 || guess > 10) { // validate range using NaN check because Number('abc') is NaN
    alert('Please enter a valid number between 1 and 10.'); // invalid input
    return; // invalid input should not consume an attempt. Guessing a number outside 1-10 is not allowed and will display the alert "Please enter a valid number between 1 and 10."
  } 

  // count only valid guesses
  guessCount += 1; // increment guess count

  console.log('current random number generated by system is', randomNumber); // for testing purposes

  // check guesses against random number

  if (guess === randomNumber) {
    const msg = '✅ Correct!'; // correct guess number is equal to random number
    document.getElementById('message').innerHTML = msg;
    // record history
    window.attemptHistory.push({ guess, message: msg, ok: true }); // correct guess
    if (typeof updateScoreboard === 'function') updateScoreboard(); // update scoreboard
    // disable controls and show Play again
    disableControls(true);
    // ensure scoreboard updated and exit
    if (typeof updateScoreboard === 'function') updateScoreboard();
    return; // correct guess
  }

  if (guess > randomNumber) {
    const msg = '😔 Too high! Try again'; // not correct number is greater than random number
    document.getElementById('message').innerHTML = msg; // provide feedback
    window.attemptHistory.push({ guess, message: msg, ok: false }); // incorrect guess
  } else {
    const msg = '😔 Too low! Try again'; // not correct number is less than random number
    document.getElementById('message').innerHTML = msg; // provide feedback
    window.attemptHistory.push({ guess, message: msg, ok: false }); // incorrect guess
  }

  // check if user has used all attempts

  if (guessCount >= guessLimit) {
    const gm = '😢 Game over! The number was ' + randomNumber; // game over message
    document.getElementById('message').innerHTML = gm; // provide game over feedback
    // record end message
    window.attemptHistory.push({ guess: null, message: gm, ok: false }); // game over
    // disable further guessing
    disableControls(true);
  } else {
    const remaining = guessLimit - guessCount; // calculate remaining attempts
    const add = ' — ' + remaining + ' attempt(s) left'; // remaining attempts message
    document.getElementById('message').innerHTML += add;  // append remaining attempts to message
    // update last history item with remaining info
    if (window.attemptHistory.length) {
      window.attemptHistory[window.attemptHistory.length - 1].message += add;
    }
  }
  if (typeof updateScoreboard === 'function') updateScoreboard(); // update scoreboard
}

// --------------------
// Scoreboard Function Logic
// --------------------

// Reset the game to initial state (generates a new random number and resets counters)

// (reset/start logic removed; Play again button will perform restart inline)

// Initialize the game and connect HTML elements to functions

function initGame() { // Initialize game and UI wiring
  const guessBtn = document.getElementById('guessBtn'); // button to submit guess
  const resetBtn = document.getElementById('resetBtn'); // button to reset game
  const limitInput = document.getElementById('limitInput'); // input for guess limit

  if (guessBtn) guessBtn.addEventListener('click', checkGuess); // wire guess button
  const playAgainBtn = document.getElementById('playAgainBtn');
  if (playAgainBtn) playAgainBtn.addEventListener('click', () => {
    // inline restart logic (previously startNewGame)
    randomNumber = Math.floor(Math.random() * 10) + 1;
    guessCount = 0;
    window.attemptHistory = [];
    const messageEl = document.getElementById('message');
    if (messageEl) messageEl.innerHTML = 'Game reset. Good luck!';
    disableControls(false);
    const guessEl = document.getElementById('userGuess');
    if (guessEl) guessEl.value = '';
    if (typeof updateScoreboard === 'function') updateScoreboard();
    playAgainBtn.style.display = 'none';
    console.log('Game reset — new number is', randomNumber);
  });
  if (limitInput) { // wire guess limit input
    limitInput.value = guessLimit; // set initial value
    limitInput.addEventListener('change', (e) => { // handle limit change
      const v = Number(e.target.value); // get new limit value
      if (!isNaN(v) && v > 0) { // validate positive integer
        setGuessLimit(v); // set new guess limit
      } else { // invalid input
        alert('Please enter a positive integer for guess limit.'); // alert invalid input
        limitInput.value = guessLimit; // reset to previous valid limit
      }
    });
  }
}

// Allow setting guess limit 

function setGuessLimit(n) {
  guessLimit = Math.max(1, Math.floor(Number(n) || 3)); // ensure minimum of 1
} 

// Expose functions to window for the HTML harness and simple testing

window.checkGuess = checkGuess; // expose checkGuess
window.initGame = initGame; // expose initGame
window.setGuessLimit = setGuessLimit; // expose setGuessLimit

// Toggle disabling of guess input and buttons. If `disabled` is true, controls are disabled.
function disableControls(disabled) {
  const guessEl = document.getElementById('userGuess');
  const guessBtn = document.getElementById('guessBtn');
  const limitInput = document.getElementById('limitInput');
  const setLimitBtn = document.getElementById('setLimitBtn');
  const playAgainBtn = document.getElementById('playAgainBtn');
  if (guessEl) { guessEl.disabled = !!disabled; }
  if (guessBtn) { guessBtn.disabled = !!disabled; }
  if (limitInput) { limitInput.disabled = !!disabled; }
  if (setLimitBtn) { setLimitBtn.disabled = !!disabled; }
  if (playAgainBtn) playAgainBtn.style.display = disabled ? '' : 'none';
}

// expose helper
window.disableControls = disableControls;

    // Connect scoreboard updates to game logic

    initGame(); // initialize game
    updateScoreboard(); // update scoreboard

    // Update scoreboard after guesses 
    const originalCheck = checkGuess; // save original checkGuess
    window.checkGuess = function() { originalCheck(); updateScoreboard(); }; // wrap checkGuess to update scoreboard

    // small helper to update scoreboard DOM
    function updateScoreboard() {
      const attemptsUsedEl = document.getElementById('attemptsUsed');
      const attemptsLeftEl = document.getElementById('attemptsLeft');
      const lastResultEl = document.getElementById('lastResult');
      const historyEl = document.getElementById('history');

      if (attemptsUsedEl) attemptsUsedEl.textContent = String(guessCount);
      if (attemptsLeftEl) attemptsLeftEl.textContent = String(Math.max(0, guessLimit - guessCount));
      const msg = document.getElementById('message');
      if (lastResultEl) lastResultEl.textContent = msg ? msg.innerText : '—';

      // render history if available
      if (historyEl && window.attemptHistory) {
        historyEl.innerHTML = '';
        window.attemptHistory.forEach((h, i) => {
          const div = document.createElement('div');
          div.className = 'history-item ' + (h.ok ? 'pass' : (h.ok === false ? 'fail' : 'info'));
          div.textContent = `${i+1}. Guess=${h.guess} — ${h.message}`;
          historyEl.appendChild(div);
        });
      }
    }
